export const NEW_MESSAGE_UPDATE = 'NEW_MESSAGE_UPDATE'
export const NEW_MESSAGE_BROADCAST = 'NEW_MESSAGE_BROADCAST'
export const FRIEND_LIST = 'FRIEND_LIST'

export const ADD_NEW_FRIEND = 'ADD_NEW_FRIEND'
export const DELETE_FRIEND = 'DELETE_FRIEND'

export const LEAVE_GROUP = 'LEAVE_GROUP'
export const ADD_NEW_GROUP = 'ADD_NEW_GROUP'
