export const SET_WEBSOCKET = 'SET_WEBSOCKET'
export const SET_MESSAGE_LIST = 'SET_MESSAGE_LIST'

export const NEW_MESSAGE_SEND = 'NEW_MESSAGE_SEND'
export const NEW_MESSAGE_RECEIVE = 'NEW_MESSAGE_RECEIVE'
