# Generated by Django 3.1.1 on 2020-10-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.BooleanField()),
                ('name', models.CharField(max_length=20)),
                ('users', models.TextField()),
                ('messages', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('chat_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=50)),
                ('friends', models.TextField(blank=True)),
            ],
        ),
    ]
