# Generated by Django 3.1.1 on 2020-11-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('ctype', models.BooleanField(default=0)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMeta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cid', models.BigIntegerField()),
                ('meta_name', models.CharField(max_length=15)),
                ('meta_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mid', models.BigAutoField(primary_key=True, serialize=False)),
                ('cid', models.BigIntegerField(default=0)),
                ('uid', models.IntegerField(default=0)),
                ('mtype', models.CharField(default='normal', max_length=15)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OfflineMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ruid', models.IntegerField(default=0)),
                ('mid', models.IntegerField(default=0)),
                ('cid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ruid', models.IntegerField(default=0)),
                ('suid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('req_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12, unique=True)),
                ('pwd', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nickname', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('meta_name', models.CharField(max_length=15)),
                ('meta_value', models.TextField()),
            ],
        ),
    ]
