# Generated by Django 3.1.1 on 2020-11-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20201112_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinerequest',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
