# Generated by Django 3.1.1 on 2020-11-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_offlinemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ruid', models.IntegerField(default=0)),
                ('suid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('req_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='offlinemessage',
            name='cid',
            field=models.IntegerField(default=0),
        ),
    ]
