# Generated by Django 3.1.1 on 2020-11-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20201114_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinemessage',
            name='fuid',
            field=models.IntegerField(default=0),
        ),
    ]
