# Generated by Django 3.1.1 on 2020-11-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_offlinemessage_fuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mid', models.IntegerField(default=0)),
                ('cid', models.IntegerField(default=0)),
            ],
        ),
    ]
